# Generated by Django 3.1.7 on 2021-03-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThinDevicesUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'مخزنه'), (2, 'جارى العمل'), (3, 'انتهى العمل')], null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_devices', models.IntegerField(blank=True, null=True)),
                ('devices_done', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_fields', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
