# Generated by Django 3.1.7 on 2021-03-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_thindevicesunits_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thindevicesunits',
            name='updated_fields',
        ),
    ]
