# Generated by Django 3.1.7 on 2021-03-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_thindevicesunits_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='thindevicesunits',
            name='build',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thindevicesunits',
            name='catoperation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thindevicesunits',
            name='center100',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thindevicesunits',
            name='center110',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thindevicesunits',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thindevicesunits',
            name='fifty_percentgy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thindevicesunits',
            name='groupwork',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thindevicesunits',
            name='mangloc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thindevicesunits',
            name='recieved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thindevicesunits',
            name='seprated_thin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thindevicesunits',
            name='twinte_five_percentgy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thindevicesunits',
            name='status',
            field=models.CharField(blank=True, choices=[('مخزن', 'مخزن'), ('جارى العمل', 'جارى العمل'), ('انتهى العمل', 'انتهى العمل')], max_length=255, null=True),
        ),
    ]
